%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Tyson/Documents/Academic/ELEN3002/Labs/lab2/measurements/MultiSim_simulation_Switch_0_to_4V.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/18 21:50:06

%% Initialize variables.
filename = '/Users/Tyson/Documents/Academic/ELEN3002/Labs/lab2/measurements/MultiSim_simulation_Switch_0_to_4V.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: text (%q)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%q%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
XTrace1 = dataArray{:, 1};
YTrace1 = dataArray{:, 2};
VarName3 = dataArray{:, 3};
XTrace2 = dataArray{:, 4};
YTrace2 = dataArray{:, 5};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Figure settings
scr = get(groot,'ScreenSize');                              % screen resolution
phi = (1 + sqrt(5))/2;
ratio = phi/3;
offset = [ scr(3)/4 scr(4)/4]; 
fig1 =  figure('Position',...                               % draw figure
    [offset(1) offset(2) scr(3)*ratio scr(4)*ratio]);
hold on
set(fig1,'numbertitle','off',...                            % Give figure useful title
    'name','MOSFET as a small-signal amplifier',...
    'Color','white',...
    'visible','off');
fontName='Helvetica';
set(0,'defaultAxesFontName', fontName);                     % Make fonts pretty
set(0,'defaultTextFontName', fontName);
set(groot,'FixedWidthFontName', 'ElroNet Monospace')      

% Create axes
ax1 = axes(fig1);
hold(ax1,'on');
box(ax1,'off');
grid off
hold on


%% Plotting
DC = plot(XTrace1,YTrace1,...
        'DisplayName','DC Voltage',...
        'Color',[0.9 0.18 0.18 .6],...                 
        'LineStyle','-',...
        'LineWidth',1.5);
hold on

V_o = plot(XTrace2,YTrace2,...
        'DisplayName','Voltage across resistor',...
        'Color',[0.18 0.18 0.9 .6],...                 
        'LineStyle','-',...
        'LineWidth',1.5);
hold on

% intercept_x = refline(0,2);
% set(intercept_x,...
%     'Color',[0.18 0.18 0.18 0.6]);
% hold on
start_sat = line([1.84 1.84],[0 5],...
    'LineStyle','--',...
    'Color',[0.18 0.18 0.18 0.6])
hold on
end_sat = line([2.15 2.15],[0 5],...
    'LineStyle','--',...
    'Color',[0.18 0.18 0.18 0.6])
hold on

% Axes and labels
ylabel(ax1,'Voltage  [V]',...
    'FontName',fontName,...
    'FontSize',16);%,...
xlabel(ax1,'Voltage  [V]',...
    'FontName',fontName,...
    'FontSize',16);
set(ax1,'FontSize',14,...
	'XMinorTick','off',...
    'YMinorTick','off');
hold on

height_txt = 3.5;

str_sat ='Saturation Region';
txt_sat = text(2.5,height_txt,str_sat,...
    'HorizontalAlignment','left',...
    'FontSize',15);    
hold on
str_triode ='"Ohmic" \newline  Triode \newline Region';
txt_triode = text(2.0025,4.9,str_triode,...
	'HorizontalAlignment','center',...
    'FontSize',15);    
hold on
str_cut ='Cut-off Region';
txt_cut = text(1.5,height_txt,str_cut,...
    'HorizontalAlignment','right',...
    'FontSize',15);    
hold on

% Labels and legend
legend1 = legend(ax1,'show');
set(legend1,...
'Position',[0.777470959760151 0.125557614144562 0.178167610819306 0.0579406864453025],...
    'Box','on',...
	'FontName',fontName,...
	'Interpreter','tex',...
	'FontSize',14);
s = get(legend1, 'string');
set(legend1, 'string', s(1:2));
% max_x = 0.01*1000;
% min_y = -3;
% max_y = 2;
% xlim(ax1,[0 max_x]);
% ylim(ax1,[min_y max_y]);
% ax1.XTick = sort([ 0:max_x/10:max_x ]);
% ax1.YTick = sort([ min_y:max_y/2:max_y ]);

% Adjust figure
pos = get(ax1, 'Position');
pos(1) = 0.05;
pos(2) = 0.065;
pos(3) = pos(3)*1.2;
pos(4) = pos(4)*1.08;
set(ax1, 'Position', pos);
hold off


set(fig1,'visible','on');

warning off;
epswrite('../report/images/Switch_data.eps');


